# Generated by Django 4.0.3 on 2022-03-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_produit_dom_produit_dop_produit_mark_produit_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='GTIN',
            field=models.BigIntegerField(),
        ),
    ]
