# Generated by Django 4.0.3 on 2022-03-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_alter_produit_gtin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='id',
        ),
        migrations.AlterField(
            model_name='produit',
            name='GTIN',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
