# Generated by Django 4.0.3 on 2022-04-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_remove_produit_id_alter_produit_gtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
